title: Welcome to my Blog
description: Charnsak's Personal Blog
author: Charnsak Srisawatsakul
logo: /assets/avatar.png
github: https://github.com/charnsak
about: CS&IT Lecturer 

baseurl: "www.charnsak.in.th"
url: "http://www.charnsak.in.th"

allowsearch: true

disqus_shortname: 
google_analytics: UA-1357289-29

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
